---
galaxy_info:
  author: DevOps Team
  description: QEMU/KVM virtual machine management for Proxmox VE
  company: Enterprise
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - proxmox
    - qemu
    - kvm
    - virtualization

dependencies:
  - role: proxmox-common
